'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

type BookingData = { link?: { title: string; description?: string; durationMinutes: number; timezone: string }; slots?: string[]; error?: string };

export default function PublicBookingPage() {
  const params = useParams<{ slug: string }>(); const slug = params.slug; const [data, setData] = useState<BookingData>({}); const [slot, setSlot] = useState(''); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [holdToken, setHoldToken] = useState(''); const [code, setCode] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { fetch(`/api/public/book/${slug}`).then(async (response) => { const body = await response.json(); setData(body); setSlot(body.slots?.[0] ?? ''); }); }, [slug]);
  async function hold(event: React.FormEvent) { event.preventDefault(); const response = await fetch(`/api/public/book/${slug}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ startAt: slot, name, email, phone }) }); const body = await response.json(); if (response.ok) { setHoldToken(body.holdToken); setMessage('We emailed you a six-digit verification code. Your slot is held for 10 minutes.'); } else setMessage(body.error); }
  async function confirm(event: React.FormEvent) { event.preventDefault(); const response = await fetch(`/api/public/book/${slug}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ holdToken, verificationCode: code }) }); const body = await response.json(); setMessage(response.ok ? `Confirmed. Zoom link: ${body.joinUrl}` : body.error); if (response.ok) setHoldToken('confirmed'); }
  return <main className="grid min-h-screen place-items-center bg-slate-50 p-5"><div className="w-full max-w-lg rounded-2xl border bg-white p-6 shadow-sm"><p className="mb-2 text-xs font-bold uppercase tracking-widest text-red-600">WolfGrid</p><h1 className="text-2xl font-semibold">{data.link?.title || 'Book a meeting'}</h1><p className="mt-1 text-sm text-slate-500">{data.link?.description || (data.link ? `${data.link.durationMinutes} minutes · shown in your local timezone` : 'Loading availability…')}</p>{data.error ? <p className="mt-5 text-red-600">{data.error}</p> : holdToken && holdToken !== 'confirmed' ? <form className="mt-6 space-y-3" onSubmit={confirm}><label className="block text-sm font-medium">Verification code<input className="mt-1 h-11 w-full rounded-md border px-3" inputMode="numeric" value={code} onChange={(event) => setCode(event.target.value)} required /></label><button className="h-11 w-full rounded-md bg-black font-semibold text-white">Confirm meeting</button></form> : holdToken === 'confirmed' ? <div className="mt-6 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800">{message}</div> : <form className="mt-6 space-y-3" onSubmit={hold}><label className="block text-sm font-medium">Available time<select className="mt-1 h-11 w-full rounded-md border px-3" value={slot} onChange={(event) => setSlot(event.target.value)}>{data.slots?.map((value) => <option key={value} value={value}>{new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}</option>)}</select></label><input className="h-11 w-full rounded-md border px-3" placeholder="Your name" value={name} onChange={(event) => setName(event.target.value)} required /><input className="h-11 w-full rounded-md border px-3" type="email" placeholder="Email" value={email} onChange={(event) => setEmail(event.target.value)} required /><input className="h-11 w-full rounded-md border px-3" placeholder="Phone (optional)" value={phone} onChange={(event) => setPhone(event.target.value)} /><button disabled={!slot} className="h-11 w-full rounded-md bg-black font-semibold text-white disabled:opacity-40">Hold this time</button></form>}{message && holdToken !== 'confirmed' ? <p className="mt-4 text-sm text-slate-600">{message}</p> : null}</div></main>;
}
