import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSalesFixture} from './field_sales_fixture.mjs';
const {db,id}=await createSalesFixture();
const admin=async q=>{await db.exec('RESET ROLE');return (await db.exec(q)).at(-1).rows;};
const actor=async n=>db.exec(`RESET ROLE;SET ROLE authenticated;SET request.jwt.claim.sub='${id(n)}'`);
const {month,today,end}=(await admin("select date_trunc('month',now() at time zone 'America/Toronto')::date::text AS month,(now() at time zone 'America/Toronto')::date::text today,(date_trunc('month',now() at time zone 'America/Toronto')+interval '1 month - 1 day')::date::text AS end"))[0];
await admin(`INSERT INTO field_sales_settings(workspace_id,enabled,currency,timezone) VALUES('${id(10)}',true,'CAD','America/Toronto'); INSERT INTO field_sales_goals(id,workspace_id,rep_id,month,target) VALUES('${id(200)}','${id(10)}','${id(2)}','${month}',5),('${id(201)}','${id(10)}',NULL,'${month}',20)`);
for(const file of ['20260916120000_pro_sales_foundation.sql','20260916121000_pro_sales_records.sql','20260916121500_pro_sales_activity.sql','20260916122000_pro_sales_reporting.sql','20260916123000_pro_sales_leaderboards.sql','20260916124000_pro_sales_goals.sql','20260916125000_pro_sales_goal_compatibility.sql','20260916126000_pro_sales_home.sql']) await db.exec(await readFile(new URL(`../migrations/${file}`,import.meta.url),'utf8'));
const cmd=async(a,d)=>(await db.query('select field_sales_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
const target=async(a,d)=>(await db.query('select field_sales_target_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
const home=async()=>(await db.query('select field_sales_home($1) d',[id(10)])).rows[0].d;
const goals=async()=>(await db.query('select field_sales_target_list($1) d',[id(10)])).rows[0].d.goals;
const imported=await admin('SELECT * FROM field_sales_targets ORDER BY id');assert.equal(imported.length,2);assert.equal(imported[0].created_by,null,'do not invent the original author');
await actor(2);let d=await home();assert.equal(d.active_goals[0].target,'5');assert.equal(d.scope,'rep');
await cmd('goal',{rep_id:id(2),month,target:8});let g=(await goals())[0];assert.equal(g.target,'8');assert.equal(g.id,id(200),'legacy update preserves modern goal identity');
await target('update',{id:g.id,version:g.version,target:'12'});
assert.equal((await db.query('select field_sales_dashboard($1) d',[id(10)])).rows[0].d.goal.target,12,'new targets update the legacy contract');
g=(await goals())[0];await target('archive',{id:g.id,version:g.version});assert.equal((await goals()).length,0);
await cmd('goal',{rep_id:id(2),month,target:6});g=(await goals())[0];assert.equal(g.id,id(200));assert.equal(g.target,'6');
await assert.rejects(()=>cmd('goal',{rep_id:id(1),month,target:1}),/goal owner/);
await actor(1);await cmd('settings',{team_revenue_visible:true});
const sale=await cmd('submit',{request_id:id(100),contact_id:id(30),rep_id:id(2),value_minor:'10003',credits:[{user_id:id(1),role:'setter',basis_points:2000},{user_id:id(2),role:'closer',basis_points:8000}]});
await cmd('verify',{id:sale.id,version:1});
d=await home();assert.equal(d.scope,'workspace');assert.equal(d.weekly.sold_value_minor,'10003');assert.equal(d.daily.sales,1);assert.equal(d.active_goals[0].actual,'1');assert.equal(d.weekly.collected_revenue_minor,'0');assert.equal(d.latest_sale.value_minor,undefined,'feed value private by default');
await actor(2);d=await home();assert.equal(d.weekly.sold_value_minor,'8003');assert.equal(d.latest_sale.value_minor,'8003');assert.equal(d.active_goals[0].actual,'1');assert.equal(d.ranking.self.rank,1);
const board=(await db.query('select field_sales_leaderboard($1,$2,$3) d',[id(10),{focus_rep:id(1),limit:1},'sold_value'])).rows[0].d;assert.equal(board.rows.length,1);assert.equal(board.has_more,false);assert.equal(board.rows[0].rank,2,'focus is applied after calculating workspace ranks');
await actor(1);await cmd('settings',{rep_revenue_visible:false,team_revenue_visible:false,feed_options:{enabled:false}});
assert.equal((await home()).latest_sale,null);await actor(2);d=await home();assert.equal(d.weekly.sold_value_minor,undefined);assert.equal(d.latest_sale.value_minor,undefined);assert.equal(d.ranking.metric,'sales','hidden revenue selects permitted featured category');
await actor(1);await cmd('cancel',{id:sale.id,reason:'Cancelled'});d=await home();assert.equal(d.weekly.sales,0);assert.equal(d.active_goals[0].actual,'0');
await db.query('select field_sales_ranking_settings($1,$2,10,$3)',[id(10),[],'sales']);d=await home();assert.equal(d.ranking.metric,null);
await actor(4);await assert.rejects(()=>home(),/Workspace access/);
// Modern custom periods remove only their own legacy representation.
await actor(2);g=(await goals())[0];await target('update',{id:g.id,version:g.version,starts_on:today,ends_on:today});
const legacy=await admin(`SELECT * FROM field_sales_goals WHERE rep_id='${id(2)}'`);assert.equal(legacy.length,0);
console.log('PASS Pro Sales Home: legacy goal migration/two-way edits, immutable provenance, credit-correct summaries, live goal recalculation, ranking focus and visibility');await db.close();
