import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {createSalesFixture} from './field_sales_fixture.mjs';
const {db,id}=await createSalesFixture();const dir=new URL('../migrations/',import.meta.url);
for(const n of (await readdir(dir)).filter(n=>/^202609161\d+_pro_sales_.*\.sql$/.test(n)).sort()) await db.exec(await readFile(new URL(n,dir),'utf8'));
await db.exec(`INSERT INTO field_sales_settings(workspace_id,enabled,currency,timezone) VALUES('${id(10)}',true,'CAD','America/Toronto')`);
const actor=async n=>db.exec(`RESET ROLE;SET ROLE authenticated;SET request.jwt.claim.sub='${id(n)}'`);
const cmd=async(a,d)=>(await db.query('select field_sales_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
const home=async()=>(await db.query('select field_sales_commission_home($1) d',[id(10)])).rows[0].d;
await actor(1);
const s=await cmd('submit',{request_id:id(410),contact_id:id(30),value_minor:'250000',commission_minor:'10001',credits:[{user_id:id(2),role:'setter',basis_points:5000},{user_id:id(3),role:'closer',basis_points:5000}]});
await actor(2);let d=await home();assert.equal(d.weekly_sales,0);assert.equal(d.weekly_commission_minor,undefined);
await actor(1);await cmd('verify',{id:s.id,version:1});assert.equal((await home()).weekly_commission_minor,'0','manager Home is personal, not team earnings');
await cmd('settings',{permissions:{commission:['member','manager']}});
await actor(2);d=await home();assert.equal(d.weekly_sales,1);assert.equal(d.weekly_commission_minor,'5000');assert.equal(d.daily_commission_minor,'5000');assert.equal(d.weekly_missing,0);
await actor(3);assert.equal((await home()).weekly_commission_minor,'5001','rounding residue allocated once');
await actor(1);const missing=await cmd('submit',{request_id:id(411),contact_id:id(31),value_minor:'500000'});await cmd('verify',{id:missing.id,version:1});d=await home();assert.equal(d.weekly_missing,1);assert.equal(d.weekly_commission_minor,'0');
await cmd('cancel',{id:s.id,reason:'Customer cancelled'});await actor(2);assert.equal((await home()).weekly_commission_minor,'0');assert.equal((await home()).weekly_sales,0);
await actor(1);await cmd('settings',{permissions:{commission:[]}});await actor(2);d=await home();assert.equal(d.commission_visible,false);for(const key of ['weekly_commission_minor','daily_commission_minor','weekly_target_minor','weekly_missing','daily_missing']) assert.equal(d[key],undefined,key+' redacted');
await actor(4);await assert.rejects(()=>home(),/Workspace access/);
console.log('PASS commission Home: personal scope, verification, exact splits, missing values, reversal, permissions and workspace isolation');await db.close();
