import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSalesFixture} from './field_sales_fixture.mjs';
const {db,id}=await createSalesFixture();
for(const file of ['20260916120000_pro_sales_foundation.sql','20260916121000_pro_sales_records.sql','20260916127000_pro_sales_entry.sql']) await db.exec(await readFile(new URL(`../migrations/${file}`,import.meta.url),'utf8'));
await db.exec(`INSERT INTO field_sales_settings(workspace_id,enabled,currency,timezone) VALUES('${id(10)}',true,'CAD','America/Toronto'); INSERT INTO contact_activities(id,contact_id,type,timestamp,status) VALUES('${id(40)}','${id(30)}','meeting',now()-interval '1 hour','completed'),('${id(41)}','${id(31)}','meeting',now()+interval '1 hour','scheduled');`);
const actor=async n=>db.exec(`RESET ROLE;SET ROLE authenticated;SET request.jwt.claim.sub='${id(n)}'`);
const entry=async(c={})=>(await db.query('select field_sales_entry($1,$2) d',[id(10),c])).rows[0].d;
const cmd=async(a,d)=>(await db.query('select field_sales_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
await actor(2);let d=await entry();assert.match(d.today,/^\d{4}-\d{2}-\d{2}$/);assert.equal(d.contacts.length,1);assert.equal(d.contacts[0].id,id(30));assert.equal(d.representatives.length,1);assert.equal(d.can_assign,false);
await assert.rejects(()=>entry({contact_id:id(31)}),/accessible/);
await assert.rejects(()=>entry({appointment_id:id(41)}),/accessible past/);
await assert.rejects(()=>entry({contact_id:id(30),campaign_id:id(999)}),/Campaign/);
d=await entry({appointment_id:id(40)});assert.equal(d.selected.id,id(30));assert.equal(d.selected.appointment_id,id(40));assert.equal(d.appointments.length,1);
await assert.rejects(()=>cmd('submit',{request_id:id(100),contact_id:id(30),value_minor:'100',setter_id:id(1)}),/assignment requires/);
const sale=await cmd('submit',{request_id:id(101),contact_id:id(30),appointment_id:id(40),value_minor:'10000',product:'Installation'});
d=await entry({contact_id:id(30)});assert.equal(d.duplicates[0].id,sale.id);assert.equal(d.duplicates[0].value_minor,undefined);assert.equal(d.can_override_duplicate,false);
assert.equal((await entry({opportunity_id:d.selected.opportunity_id})).selected.id,id(30));
await assert.rejects(()=>entry({opportunity_id:d.selected.opportunity_id,contact_id:id(31)}),/accessible opportunity/);
await actor(1);d=await entry({contact_id:id(30)});assert.equal(d.can_override_duplicate,true);assert.equal(d.representatives.length,3);
await assert.rejects(()=>cmd('submit',{request_id:id(102),contact_id:id(30),rep_id:id(2),value_minor:'30000'}),/existing sale/);
const extra=await cmd('submit',{request_id:id(103),contact_id:id(30),rep_id:id(2),value_minor:'30000',job_identifier:'Second job',duplicate_override_reason:'Separate service contract'});assert.notEqual(extra.id,sale.id);
await assert.rejects(()=>entry({unexpected:'value'}),/Unknown sale/);
await assert.rejects(()=>entry({property_key:'wrong',contact_id:id(30)}),/property/);
await actor(4);await assert.rejects(()=>entry(),/Workspace access/);
console.log('PASS Pro Sales entry: authorized context resolution, past appointments, opportunity consistency, assignment permissions and separate-job warning/override');await db.close();
