import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createSalesFixture } from './field_sales_fixture.mjs';

const { db, id } = await createSalesFixture();
await db.exec(await readFile(new URL('../migrations/20260916120000_pro_sales_foundation.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../migrations/20260916121000_pro_sales_records.sql', import.meta.url), 'utf8'));
const actor = async n => db.exec(`RESET ROLE; SET ROLE authenticated; SET request.jwt.claim.sub='${id(n)}';`);
const sql = async (query, params) => { await db.exec('RESET ROLE'); return params ? (await db.query(query, params)).rows : (await db.exec(query)).at(-1).rows; };
const command = async (action, data) => (await db.query('select field_sales_command($1,$2,$3::jsonb) result', [id(10), action, JSON.stringify(data)])).rows[0].result;
const saleRow = async sale => (await sql('select * from field_sales where id=$1', [sale.id]))[0];
const failure = async (fn, pattern) => assert.rejects(fn, pattern);
await sql(`ALTER TABLE contacts ADD COLUMN address text, ADD COLUMN building_id text;
 UPDATE contacts SET address='123 Main Street',building_id='building-a' WHERE id='${id(30)}';
 INSERT INTO field_sales_settings(workspace_id,enabled) VALUES('${id(10)}',true);
 INSERT INTO field_sales_teams(id,workspace_id,name) VALUES('${id(200)}','${id(10)}','Team Alpha'),('${id(201)}','${id(10)}','Team Beta');
 INSERT INTO field_sales_team_memberships(workspace_id,team_id,user_id,starts_at) VALUES('${id(10)}','${id(200)}','${id(2)}',now()-interval '30 days');
 INSERT INTO sessions VALUES('${id(220)}','${id(10)}','${id(2)}','${id(20)}'),('${id(221)}','${id(11)}','${id(4)}',null);
 INSERT INTO session_events(id,session_id,building_id,created_at,event_type) VALUES
 ('${id(222)}','${id(220)}','building-a',now()-interval '1 hour','conversation'),
 ('${id(223)}','${id(221)}','building-a',now()-interval '1 hour','conversation');`);
await actor(2);
await failure(() => command('settings', { currency: 'CAD', timezone: 'America/Toronto' }), /administrator/);
await actor(1);
await command('settings', { currency: 'CAD', timezone: 'America/Toronto' });
await failure(()=>command('settings',{feed_options:{contract_values:'yes'}}),/Invalid feed/);
await failure(()=>command('settings',{permissions:{collect:['stranger']}}),/Invalid permission role/);
const today = (await sql("select (now() at time zone 'America/Toronto')::date::text d"))[0].d;
const stamp = (await sql('select now()::text t'))[0].t;
const payload = { request_id: id(300), contact_id: id(30), value_minor: '2200001', original_event_id: id(222), sold_on: today };
await actor(2);
const sale = await command('submit', payload);
assert.deepEqual(await command('submit', payload), sale, 'sale submission retry');
await failure(() => command('submit', { ...payload, value_minor: '999999' }), /Request ID/);
await failure(() => command('submit', { ...payload, request_id: id(301) }), /existing sale/);
await failure(() => command('submit', { ...payload, request_id: id(302), contact_id: id(33) }), /accessible/);
await failure(() => command('submit', { ...payload, request_id: id(303), original_event_id: id(223) }), /Original activity/);
await failure(() => command('verify', { id: sale.id, version: 1 }), /permission/);
let s = await saleRow(sale);
assert.equal(s.status, 'pending'); assert.equal(s.attribution_confidence, 'confirmed');
assert.equal(s.property_key, 'building-a'); assert.equal(s.property_snapshot.address, '123 Main Street');
assert.equal(s.setter_id, id(2)); assert.equal(s.closer_id, id(2));
assert.equal(s.team_id, id(200)); assert.equal(s.team_name_snapshot, 'Team Alpha');
assert.equal(s.campaign_id, id(20)); assert.equal(s.territory_id, id(21)); assert.ok(s.opportunity_id);
assert.equal((await sql('select sales_status from contacts where id=$1',[id(30)]))[0].sales_status, 'sold');
assert.equal((await sql('select stage_key from field_sales_opportunities where id=$1',[s.opportunity_id]))[0].stage_key,'won');
await actor(1);
await failure(() => command('verify', { id: sale.id, version: 999 }), /changed/);
await command('verify', { id: sale.id, version: 1 });
await command('verify', { id: sale.id, version: 1 });
const split = { id: sale.id, version: 2, request_id: id(310), reason: 'Jake set; Chris closed', setter_id: id(2), closer_id: id(3),
 credits: [{ user_id: id(2), role: 'setter', basis_points: 3500 }, { user_id: id(3), role: 'closer', basis_points: 6500 }] };
const corrected = await command('attribution', split);
assert.deepEqual(await command('attribution', split), corrected, 'attribution retry uses original request');
await failure(() => command('attribution', { ...split, request_id: id(311), version: 3, credits: [{ user_id: id(2), role: 'setter', basis_points: 3500 }] }), /100 percent/);
await failure(() => command('attribution', { ...split, request_id: id(312), version: 3, credits: [{ user_id: id(4), role: 'closer', basis_points: 10000 }] }), /Invalid credit/);
await failure(() => command('attribution', { ...split, request_id: id(313), version: 3, value_minor: '1' }), /non-attribution/);
assert.equal((await sql('select sum(value_minor)::text amount from field_sales where workspace_id=$1 and status=\'verified\'', [id(10)]))[0].amount,'2200001','company revenue counted once');
assert.equal((await sql('select sum(basis_points)::text share from field_sales_credits where sale_id=$1',[sale.id]))[0].share,'10000');
await sql(`UPDATE field_sales_team_memberships SET ends_at=now() WHERE workspace_id='${id(10)}' AND user_id='${id(2)}';
 INSERT INTO field_sales_team_memberships(workspace_id,team_id,user_id) VALUES('${id(10)}','${id(201)}','${id(2)}');`);
s = await saleRow(sale); assert.equal(s.team_name_snapshot,'Team Alpha');
await actor(1);
await command('edit', { id:s.id, version:s.version, product:'Roofing', notes:'Scope confirmed' });
s = await saleRow(sale); assert.equal(s.team_name_snapshot,'Team Alpha');
assert.equal((await sql('select team_name_snapshot from field_sales_credits where sale_id=$1 and user_id=$2',[sale.id,id(2)]))[0].team_name_snapshot,'Team Alpha');
await actor(1);
const payment = { id: sale.id, request_id: id(320), amount_minor:'500000', occurred_at:stamp, note:'Deposit' };
const paid = await command('collect',payment);
assert.deepEqual(await command('collect',payment),paid);
await failure(() => command('collect',{...payment,amount_minor:'600000'}),/Request ID/);
await failure(() => command('collect',{...payment,request_id:id(321),amount_minor:'-1'}),/positive/);
await failure(() => command('collect',{...payment,request_id:id(322),occurred_at:'2099-01-01T00:00:00Z'}),/Payment date/);
await failure(() => command('refund_payment',{...payment,request_id:id(323),amount_minor:'500001'}),/exceed/);
assert.equal((await sql('select sum(amount_minor)::text cash from field_sales_payments where sale_id=$1',[sale.id]))[0].cash,'500000');
s=await saleRow(sale); assert.equal(s.completed_value_minor,0); assert.equal(s.value_minor,2200001);
await actor(1);
await command('complete',{id:sale.id,completed_on:today});
s=await saleRow(sale); assert.equal(s.completed_value_minor,2200001); assert.equal(s.fulfillment_status,'completed');
await actor(1);
await command('cancel',{id:sale.id,reason:'Customer cancelled after partial installation'});
await command('cancel',{id:sale.id,reason:'Customer cancelled after partial installation'});
s=await saleRow(sale); assert.equal(s.status,'cancelled'); assert.ok(s.cancelled_at);
assert.equal(s.completed_value_minor,2200001,'historical completed value preserved');
assert.equal((await sql('select sum(amount_minor)::text cash from field_sales_payments where sale_id=$1',[sale.id]))[0].cash,'500000','cancellation does not invent a cash refund');
assert.equal((await sql('select count(*)::int n from field_sales where status=\'verified\' and id=$1',[sale.id]))[0].n,0);
await actor(1);
await command('refund_payment',{...payment,request_id:id(324),amount_minor:'500000'});
assert.equal((await sql('select sum(amount_minor)::text cash from field_sales_payments where sale_id=$1',[sale.id]))[0].cash,'0');
const audit=await sql('select action from field_sales_events where sale_id=$1',[sale.id]);
assert.equal(audit.filter(x=>x.action==='verify').length,1);
assert.equal(audit.filter(x=>x.action==='cancel').length,1);
assert.ok(audit.some(x=>x.action==='collect')); assert.ok(audit.some(x=>x.action==='refund_payment'));
await actor(2);
await failure(()=>db.query('select * from field_sales_payments'),/permission denied/);
await failure(()=>db.query('select * from field_sales_credits'),/permission denied/);
await failure(()=>db.query('select field_sales_command_v1($1,$2,$3)',[id(10),'submit',payload]),/permission denied/);
const replacement=await command('submit',{...payload,request_id:id(330),replaces_id:sale.id});
await failure(()=>command('submit',{...payload,request_id:id(331),job_identifier:'second-job',duplicate_override_reason:'Separate scope'}),/existing sale/);
await actor(1);
const separate=await command('submit',{...payload,request_id:id(332),job_identifier:'second-job',duplicate_override_reason:'Detached garage, separate contract'});
assert.notEqual(separate.id,replacement.id,'legitimate multiple jobs allowed by manager');
await failure(()=>command('submit',{...payload,request_id:id(333),job_identifier:'second-job',duplicate_override_reason:'Retry with new key'}),/field_sales_job_identity/);
await command('reject',{id:separate.id,reason:'Customer has not signed'});
await command('settings',{verification_required:false,rep_revenue_visible:false});
await actor(3);
const automatic=await command('submit',{request_id:id(334),contact_id:id(32),value_minor:'1250'});
assert.equal(automatic.status,'verified','configured automatic verification');
await actor(2);
await failure(()=>command('collect',{...payment,id:automatic.id,request_id:id(335)}),/permission/);
await actor(4);
await failure(()=>command('collect',{...payment,request_id:id(336)}),/Workspace access/);
await actor(1);
const record = async sid => (await db.query('select field_sales_record($1,$2) result',[id(10),sid])).rows[0].result;
let detail = await record(sale.id);
assert.equal(detail.value_minor,'2200001'); assert.equal(detail.collected_revenue_minor,'0');
assert.equal(detail.completed_value_minor,'2200001'); assert.equal(detail.net_sold_value_minor,'0');
assert.equal(detail.credits.reduce((total,x)=>total+BigInt(x.credited_value_minor),0n),2200001n,'rounded split shares sum exactly');
assert.equal(detail.payments.length,2); assert.ok(detail.timeline.some(x=>x.kind==='original_activity'));
await command('attribution',{id:replacement.id,version:1,reason:'Three participants, one without revenue credit',credits:[
 {user_id:id(1),role:'contributor',basis_points:3333},{user_id:id(2),role:'closer',basis_points:6667},{user_id:id(3),role:'setter',basis_points:0}
]});
const zeroShare=await record(replacement.id);
assert.equal(zeroShare.credits.find(x=>x.user_id===id(3)).credited_value_minor,'0','rounding must not credit a zero-share rep');
assert.equal(zeroShare.credits.reduce((n,x)=>n+BigInt(x.credited_value_minor),0n),2200001n);
await actor(2);
detail=await record(sale.id);
assert.equal(detail.value_minor,undefined); assert.equal(detail.completed_value_minor,undefined); assert.equal(detail.collected_revenue_minor,undefined);
assert.equal(detail.payments.length,0); assert.ok(detail.credits.every(x=>x.credited_value_minor===undefined));
assert.ok(detail.events.every(x=>x.value_minor===undefined && x.amount_minor===undefined));
const legacy = (await db.query('select field_sales_dashboard($1) result',[id(10)])).rows[0].result;
assert.equal(legacy.totals.revenue_minor,undefined); assert.ok(legacy.sales.every(x=>x.value_minor===undefined));
const history=(await db.query('select field_sales_history($1,$2) result',[id(10),sale.id])).rows[0].result;
assert.ok(history.every(x=>x.value_minor===undefined && x.amount_minor===undefined));
await failure(()=>db.query('select field_sales_dashboard_v1($1)',[id(10)]),/permission denied/);
await failure(()=>record(automatic.id),/Sale access/);
await actor(4); await failure(()=>record(sale.id),/Workspace access/);
await sql('select 1');
const bounds=async(zone,period,start,end,now)=>(await db.query('select * from field_sales_period_bounds($1,$2,$3,$4,$5)',[zone,period,start,end,now])).rows[0];
const spring=await bounds('America/Toronto','today',null,null,'2026-03-08T16:00:00Z');
assert.equal((new Date(spring.end_at)-new Date(spring.start_at))/3600000,23);
const fall=await bounds('America/Toronto','today',null,null,'2026-11-01T16:00:00Z');
assert.equal((new Date(fall.end_at)-new Date(fall.start_at))/3600000,25);
const custom=await bounds('America/Toronto','custom','2026-09-01','2026-09-15','2026-09-15T16:00:00Z');
assert.equal(new Date(custom.end_day).toISOString().slice(0,10),'2026-09-16'); assert.equal(new Date(custom.previous_end).toISOString().slice(0,10),'2026-09-01');
await failure(()=>bounds('America/Toronto','custom','2026-09-15','2026-09-01',stamp),/valid reporting/);
console.log('PASS Pro Sales foundation: attribution, splits, historical teams, verification, multiple jobs, payments/refunds, audit, permissions and DST bounds');
await db.close();
