import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {createSalesFixture} from './field_sales_fixture.mjs';
const {db,id}=await createSalesFixture();const directory=new URL('../migrations/',import.meta.url);
for(const file of (await readdir(directory)).filter(f=>/^202609161\d+_pro_sales_.*\.sql$/.test(f)||/^2026091712\d+_appointment_.*\.sql$/.test(f)).sort()) await db.exec(await readFile(new URL(file,directory),'utf8'));
await db.exec(`INSERT INTO field_sales_settings(workspace_id,enabled,currency,timezone) VALUES('${id(10)}',true,'CAD','America/Toronto');
INSERT INTO contact_activities(id,contact_id,type,timestamp,status) VALUES('${id(40)}','${id(30)}','meeting',now()-interval '1 hour','completed');`);
const actor=async n=>db.exec(`RESET ROLE;SET ROLE authenticated;SET request.jwt.claim.sub='${id(n)}'`);
const rpc=async(name,args)=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) d`,args)).rows[0].d;
const cmd=(a,p)=>rpc('field_sales_command',[id(10),a,p]);
const report=(f={})=>rpc('field_sales_report',[id(10),{period:'week',...f}]);
const home=()=>rpc('field_sales_home',[id(10)]);
const commission=()=>rpc('field_sales_commission_home',[id(10)]);
const ranks=()=>rpc('field_sales_leaderboard',[id(10),{period:'week'},'sold_value']);
const goals=()=>rpc('field_sales_target_list',[id(10),{}]);
await actor(1);await cmd('settings',{team_revenue_visible:true,permissions:{commission:['member','manager']}});
const dates=(await db.query("select date_trunc('week',now() at time zone 'America/Toronto')::date::text start,(date_trunc('week',now() at time zone 'America/Toronto')::date+6)::text finish")).rows[0];
const goal=await rpc('field_sales_target_command',[id(10),'create',{request_id:id(80),scope:'rep',scope_id:id(2),metric:'commission',target:'60000',title:'Weekly commission',starts_on:dates.start,ends_on:dates.finish}]);
const sale=await cmd('submit',{request_id:id(81),contact_id:id(30),appointment_id:id(40),value_minor:'250000',commission_minor:'25000'});
await actor(2);assert.equal((await report()).summary.sales,0);assert.equal((await commission()).weekly_commission_minor,'0');assert.equal((await home()).weekly.sales,0);
await actor(1);await cmd('verify',{id:sale.id,version:1});assert.equal((await report({scope:'team'})).summary.sold_value_minor,'250000');assert.equal((await commission()).weekly_commission_minor,'0','converter does not receive the rep commission');
await actor(2);let d=await report();assert.equal(d.summary.sales,1);assert.equal(d.summary.sold_value_minor,'250000');assert.equal(d.summary.collected_revenue_minor,'0');assert.equal(d.metrics.close_rate,'100.00');
assert.equal((await home()).weekly.sold_value_minor,'250000');let c=await commission();assert.equal(c.weekly_commission_minor,'25000');assert.equal(c.weekly_target_minor,'60000');assert.equal(c.weekly_sales,1);
let board=await ranks();assert.equal(board.rows.find(r=>r.rep_id===id(2)).value,'250000');
let g=await goals();assert.equal(g.goals.find(r=>r.id===goal.id).actual,'25000');
let detail=await rpc('field_sales_record',[id(10),sale.id]);assert.equal(detail.appointment_id,id(40));assert.equal(detail.rep_id,id(2));
await actor(1);await cmd('cancel',{id:sale.id,reason:'Customer cancelled'});
await actor(2);assert.equal((await report()).summary.sales,0);assert.equal((await home()).weekly.sales,0);assert.equal((await commission()).weekly_commission_minor,'0');assert.equal((await goals()).goals.find(r=>r.id===goal.id).actual,'0');
board=await ranks();assert.equal(board.rows.find(r=>r.rep_id===id(2)).value,'0');
await actor(1);await cmd('submit',{request_id:id(82),contact_id:id(30),appointment_id:id(40),value_minor:'250000'});
await db.exec('RESET ROLE');await assert.rejects(()=>db.query("update field_sales set status='verified' where id=$1",[sale.id]),/field_sales_one_active_appointment/);
await actor(4);await assert.rejects(()=>home(),/Workspace access/);await assert.rejects(()=>commission(),/Workspace access/);
await db.exec('RESET ROLE');assert.equal((await db.query('select status from field_sales where id=$1',[sale.id])).rows[0].status,'cancelled');
assert.equal((await db.query("select count(*)::int n from pg_indexes where indexname='field_sales_one_active_appointment'")).rows[0].n,1);
console.log('PASS appointment → sale → verification → rep/company reports, Home, commission goal and leaderboard → reversal; converter attribution and workspace privacy');await db.close();
