import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSalesFixture} from './field_sales_fixture.mjs';

const {db,id}=await createSalesFixture();
for(const file of ['20260916120000_pro_sales_foundation.sql','20260916121000_pro_sales_records.sql','20260916121500_pro_sales_activity.sql','20260916122000_pro_sales_reporting.sql','20260916123000_pro_sales_leaderboards.sql']) {
  await db.exec(await readFile(new URL(`../migrations/${file}`,import.meta.url),'utf8'));
}
const actor=async n=>db.exec(`RESET ROLE;SET ROLE authenticated;SET request.jwt.claim.sub='${id(n)}';`);
const admin=async q=>{await db.exec('RESET ROLE');return (await db.exec(q)).at(-1).rows;};
const cmd=async(action,data)=>(await db.query('select field_sales_command($1,$2,$3) d',[id(10),action,data])).rows[0].d;
const report=async(filter={})=>(await db.query('select field_sales_report($1,$2) d',[id(10),filter])).rows[0].d;
const {today,prior,stamp}= (await admin("select (now() at time zone 'America/Toronto')::date::text today,(date_trunc('month',now() at time zone 'America/Toronto')-interval '1 day')::date::text prior,now()::text stamp"))[0];
await admin(`UPDATE contacts SET created_at=now()-interval '90 days';
 INSERT INTO field_sales_settings(workspace_id,enabled) VALUES('${id(10)}',true);
 INSERT INTO field_sales_teams(id,workspace_id,name) VALUES('${id(90)}','${id(10)}','Alpha');
 INSERT INTO field_sales_team_memberships(workspace_id,team_id,user_id,starts_at) VALUES('${id(10)}','${id(90)}','${id(1)}',now()-interval '90 days');
 INSERT INTO contacts(id,workspace_id,user_id,full_name,campaign_id,created_at) VALUES('${id(40)}','${id(10)}','${id(2)}','Cohort customer','${id(20)}',now()-interval '1 hour');
 INSERT INTO contact_activities(id,contact_id,type,timestamp,status) VALUES('${id(41)}','${id(40)}','meeting',now()-interval '30 minutes','completed'),('${id(42)}','${id(40)}','meeting',now()-interval '20 minutes','scheduled');
 INSERT INTO sessions VALUES('${id(50)}','${id(10)}','${id(2)}','${id(20)}');
 INSERT INTO session_events(id,session_id,building_id,created_at,event_type) VALUES
 ('${id(51)}','${id(50)}','a',now()-interval '1 hour','conversation'),('${id(52)}','${id(50)}','a',now()-interval '30 minutes','conversation'),
 ('${id(53)}','${id(50)}','b',now()-interval '1 hour','completed_manual'),('${id(54)}','${id(50)}','b',now()-interval '30 minutes','completion_undone');`);
await actor(1);await cmd('settings',{currency:'CAD',timezone:'America/Toronto'});
const old=await cmd('submit',{request_id:id(100),contact_id:id(31),value_minor:'10001',sold_on:prior,product:'Roofing',credits:[{user_id:id(1),role:'closer',basis_points:2500},{user_id:id(2),role:'setter',basis_points:7500}]});
await cmd('verify',{id:old.id,version:1});
await cmd('complete',{id:old.id,completed_on:today,completed_value_minor:'9000'});
await cmd('collect',{id:old.id,request_id:id(101),amount_minor:'6000',occurred_at:stamp});
await cmd('cancel',{id:old.id,reason:'Cancelled after partial completion'});
const current=await cmd('submit',{request_id:id(102),contact_id:id(40),rep_id:id(2),setter_id:id(1),closer_id:id(2),appointment_id:id(41),value_minor:'10003',sold_on:today,product:'Solar',credits:[{user_id:id(1),role:'setter',basis_points:2000},{user_id:id(2),role:'closer',basis_points:8000}]});
await cmd('verify',{id:current.id,version:1});
let d=await report({scope:'team',period:'month'});
assert.equal(d.summary.sales,1);assert.equal(d.summary.sold_value_minor,'10003');
assert.equal(d.summary.completed_value_minor,'9000');assert.equal(d.summary.collected_revenue_minor,'6000');
assert.equal(d.summary.cancellations_minor,'0','contract reversal belongs to original sold period');
assert.equal(d.metrics.doors,1);assert.equal(d.metrics.conversations,1);
assert.equal(d.metrics.leads,1);assert.equal(d.metrics.leads_converted,1);
assert.equal(d.metrics.appointments,2);assert.equal(d.metrics.appointments_completed,1,'elapsed scheduled appointment is not automatically completed');
assert.equal(d.metrics.appointments_converted,1);assert.equal(d.metrics.close_rate,'100.00');assert.equal(d.metrics.close_rate_rank_eligible,false);
assert.equal(d.summary.average_ticket_minor,'10003');
assert.equal(d.sales.length,1);assert.equal(d.groups[0].sales,1);
const past=await report({scope:'team',period:'previous_month'});
assert.equal(past.summary.gross_sold_minor,'10001');assert.equal(past.summary.cancellations_minor,'10001');assert.equal(past.summary.sold_value_minor,'0');
assert.equal(past.summary.completed_value_minor,'0');assert.equal(past.summary.collected_revenue_minor,'0');
const owner=await report({scope:'team',rep:id(1)}),rep=await report({scope:'team',rep:id(2)});
assert.equal(BigInt(owner.summary.sold_value_minor)+BigInt(rep.summary.sold_value_minor),10003n);
assert.equal(owner.summary.setter_sales,1);assert.equal(rep.summary.closer_sales,1);
assert.equal(BigInt(owner.summary.collected_revenue_minor)+BigInt(rep.summary.collected_revenue_minor),6000n);
assert.equal(BigInt(owner.summary.completed_value_minor)+BigInt(rep.summary.completed_value_minor),9000n);
const filtered=await report({scope:'team',product:'Solar',dimension:'product'});
assert.equal(filtered.summary.sold_value_minor,'10003');assert.equal(filtered.summary.collected_revenue_minor,'0');
assert.equal(filtered.metrics.available,false);assert.equal(filtered.metrics.close_rate,null,'do not condition denominator on sold product');
assert.equal(filtered.groups[0].name,'Solar');
assert.equal((await report({scope:'team',territory:id(21)})).summary.sales,1);
assert.equal((await report({scope:'team',campaign:id(999)})).summary.sales,0);
assert.equal((await report({scope:'team',team:id(90),period:'previous_month'})).summary.gross_sold_minor,'10001');
const paged=await report({scope:'team',period:'all',limit:1});assert.equal(paged.total_records,2);assert.equal(paged.has_more,true);
const next=await report({scope:'team',period:'all',limit:1,offset:1});assert.equal(next.has_more,false);assert.notEqual(paged.sales[0].id,next.sales[0].id);
const custom=await report({scope:'team',period:'custom',start:today,end:today});assert.equal(custom.summary.sold_value_minor,'10003');
assert.equal(custom.period_start,today);assert.equal(custom.period_end,today);
await assert.rejects(()=>report({scope:'team',limit:201}),/Invalid report/);
await assert.rejects(()=>report({scope:'team',dimension:'untrusted_sql'}),/dimension/);
await assert.rejects(()=>report({scope:'team',arbitrary:'ignored'}),/Unknown report/);
// Counts and their drilldowns share one source-record definition.
const drill=async(kind,filter={scope:'team'})=>(await db.query('select field_sales_drilldown($1,$2,$3) d',[id(10),filter,kind])).rows[0].d;
for(const kind of ['doors','conversations','leads','appointments','appointments_completed','opportunities','sales','completed']) {
 const x=await drill(kind);assert.equal(x.total_records,Number(x.expected_count));assert.equal(x.rows.length,x.total_records);
}
const payments=await drill('collected');assert.equal(payments.rows.reduce((a,x)=>a+BigInt(x.value_minor),0n),6000n);
await assert.rejects(()=>drill(null),/Invalid funnel/);
await assert.rejects(()=>drill('doors',{scope:'team',product:'Solar'}),/Remove sale/);
const board=async(metric,filter={})=>(await db.query('select field_sales_leaderboard($1,$2,$3) d',[id(10),filter,metric])).rows[0].d;
let ranks=await board('sold_value');
assert.equal(ranks.rows.reduce((a,x)=>a+BigInt(x.value),0n),10003n,'ranked split shares reconcile to company');
assert.equal(JSON.stringify(ranks).includes('Cohort customer'),false,'leaderboards contain no customer identity');
assert.equal((await board('sales')).rows.filter(x=>x.value==='1').every(x=>x.rank===1),true,'ties share a rank');
assert.equal((await board('close_rate')).total_ranked,0,'small samples excluded');
await cmd('settings',{minimum_close_opportunities:2});
await admin(`INSERT INTO contact_activities(id,contact_id,type,timestamp,status) VALUES('${id(43)}','${id(40)}','meeting',now()-interval '10 minutes','completed'),('${id(44)}','${id(32)}','meeting',now()-interval '10 minutes','completed');`);
await actor(1);
const tiny=await cmd('submit',{request_id:id(105),contact_id:id(32),rep_id:id(3),appointment_id:id(44),value_minor:'9900'});
await cmd('verify',{id:tiny.id,version:1});
ranks=await board('close_rate');assert.equal(ranks.total_ranked,1);assert.equal(ranks.rows[0].rep_id,id(2));assert.equal(ranks.rows[0].value,'50.00');
assert.equal(ranks.rows.some(x=>x.rep_id===id(3)),false,'one of one cannot outrank one of two');
await assert.rejects(()=>board('close_rate',{product:'Solar'}),/not available/);
await assert.rejects(()=>board('doors',{scope:'team'}),/Unknown leaderboard/);
const rankingSettings=async categories=>db.query('select field_sales_ranking_settings($1,$2,$3,$4)',[id(10),categories,2,'sales']);
await rankingSettings([]);assert.equal((await board(null)).settings.leaderboard_categories.length,0,'admin can re-enable disabled leaderboards');
await rankingSettings(['sales']);assert.deepEqual((await board('sales')).categories,['sales']);
assert.equal((await board('sales')).rows.every(x=>x.metrics.close_rate===undefined && x.metrics.sold_value_minor===undefined),true,'disabled categories have no hidden raw values');
await assert.rejects(()=>rankingSettings(['unrecognized']),/Unknown leaderboard/);
await cmd('settings',{rep_revenue_visible:false,team_revenue_visible:false});
await actor(2);assert.equal((await report(null)).filter.rep,id(2),'null filter must remain scoped to the signed-in rep');await assert.rejects(()=>rankingSettings(['doors']),/administrator/);d=await report();
assert.equal(d.summary.sales,1);assert.equal(d.summary.sold_value_minor,undefined);assert.equal(d.previous.sold_value_minor,undefined);
assert.equal(d.sales[0].value_minor,undefined);assert.equal(d.groups[0].sold_value_minor,undefined);assert.equal(d.change_percent.sold_value_minor,undefined);
assert.equal(d.metrics.revenue_per_door_minor,null);
await assert.rejects(()=>report({scope:'team'}),/Team reporting/);
assert.equal((await report({rep:id(1)})).filter.rep,id(2),'self scope cannot impersonate another representative');
await assert.rejects(()=>db.query('select field_sales_financial_summary($1,$2,$3,$4,$5,true)',[id(10),{},today,today,'UTC']),/permission denied/);
await assert.rejects(()=>drill('leads',{scope:'team'}),/Team reporting/);
assert.equal((await drill('leads',{})).rows.every(x=>x.rep_id===id(2)),true);
await assert.rejects(()=>board('sold_value'),/not available/);
const publicBoard=await board('sales');assert.equal(publicBoard.rows.every(x=>x.metrics.sold_value_minor===undefined),true);
await assert.rejects(()=>db.query('select * from field_sales_activity_rows($1,$2,$3,$4,$5)',[id(10),{},today,today,'UTC']),/permission denied/);
await actor(4);await assert.rejects(()=>report(),/Workspace access/);
console.log('PASS Pro Sales reporting: exact split revenue, independent completion/cash dates, reversals, cohorts, filters, pagination, privacy and role isolation');
await db.close();
