import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSalesFixture} from './field_sales_fixture.mjs';
const {db,id}=await createSalesFixture();
for(const file of ['20260916120000_pro_sales_foundation.sql','20260916121000_pro_sales_records.sql','20260916128000_pro_sales_pipeline.sql']) await db.exec(await readFile(new URL(`../migrations/${file}`,import.meta.url),'utf8'));
await db.exec(`INSERT INTO field_sales_settings(workspace_id,enabled,currency,timezone) VALUES('${id(10)}',true,'CAD','America/Toronto')`);
const actor=async n=>db.exec(`RESET ROLE;SET ROLE authenticated;SET request.jwt.claim.sub='${id(n)}'`);
const cmd=async(a,d)=>(await db.query('select field_sales_pipeline_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
const sales=async(a,d)=>(await db.query('select field_sales_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
const board=async()=>(await db.query('select field_sales_workbench($1) d',[id(10)])).rows[0].d;
await actor(1);
let one=await cmd('opportunity',{contact_id:id(30),stage_key:'proposal',expected_value_minor:'120000'});
assert.equal(one.user_id,id(2),'manager editing keeps lead owner');
let two=await cmd('opportunity',{contact_id:id(31),stage_key:'opportunity',expected_value_minor:'50000'});
let d=await board();assert.equal(d.scope,'workspace');assert.equal(d.open_pipeline.value_minor,'170000');assert.equal(d.open_pipeline.count,2);assert.equal(d.opportunities.length,2);assert.equal(d.task_leads.length,1);
await assert.rejects(()=>cmd('opportunity',{contact_id:id(30),version:1,stage_key:'won'}),/Mark as sold/);
const entered=one.stage_entered_at;one=await cmd('opportunity',{contact_id:id(30),version:1,stage_key:'proposal',notes:'Call later'});assert.equal(one.stage_entered_at,entered,'editing notes does not reset time in stage');
await assert.rejects(()=>cmd('opportunity',{contact_id:id(30),version:1,stage_key:'lost'}),/changed/);
one=await cmd('opportunity',{contact_id:id(30),version:2,stage_key:'lost',loss_reason:'price',loss_note:'Budget below estimate'});assert.equal(one.loss_reason,'price');assert.ok(one.lost_at);
d=await board();assert.equal(d.open_pipeline.value_minor,'50000');assert.equal(d.losses[0].reason,'price');assert.equal(d.losses[0].percent,'100.00');
await assert.rejects(()=>cmd('stage',{key:'lost',label:'New',position:90,probability:0,kind:'open'}),/outcome type/);
await actor(2);d=await board();assert.equal(d.scope,'self');assert.equal(d.opportunities.length,1);assert.equal(d.summary.reduce((n,x)=>n+x.count,0),1,'rep summaries do not contain workspace opportunities');
await assert.rejects(()=>cmd('opportunity',{contact_id:id(31),stage_key:'lost',version:1}),/accessible/);
await actor(1);await sales('settings',{rep_revenue_visible:false});await actor(2);
d=await board();assert.equal(d.money_visible,false);assert.equal(d.opportunities[0].expected_value_minor,undefined);assert.equal(d.summary.every(x=>x.value_minor===undefined),true);
await assert.rejects(()=>cmd('opportunity',{contact_id:id(30),stage_key:'lost',version:3,expected_value_minor:'1'}),/Revenue permission/);
one=await cmd('opportunity',{contact_id:id(30),stage_key:'follow_up',version:3,notes:'Customer reopened discussion'});assert.equal(one.expected_value_minor,undefined);assert.equal(one.loss_reason,null);
await actor(1);d=await board();assert.equal(d.opportunities.find(x=>x.contact_id===id(30)).expected_value_minor,'120000','hidden amount was preserved');
const sale=await sales('submit',{request_id:id(90),contact_id:id(31),value_minor:'50000'});
await assert.rejects(()=>cmd('opportunity',{contact_id:id(31),version:2,stage_key:'lost',loss_reason:'price'}),/connected sale/);
await db.exec(`RESET ROLE;UPDATE field_sales_opportunities SET updated_at=now()-interval '4 days' WHERE contact_id='${id(30)}';UPDATE contacts SET user_id='${id(3)}' WHERE id='${id(30)}'`);
await actor(2);assert.equal((await board()).opportunities.length,0);assert.equal((await board()).summary.reduce((n,x)=>n+x.count,0),0);
await actor(3);d=await board();assert.equal(d.opportunities.length,2,'admin retains workspace scope');assert.equal(d.open_pipeline.stalled,1);
await actor(4);await assert.rejects(()=>board(),/Workspace access/);
console.log('PASS Pro pipeline: manager/rep scopes, hidden value preservation, real-sale stage guards, loss/reopen audit semantics, versions and stale opportunities');await db.close();
