import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSalesFixture} from './field_sales_fixture.mjs';
const {db,id}=await createSalesFixture();
for(const file of ['20260916120000_pro_sales_foundation.sql','20260916121000_pro_sales_records.sql','20260916121500_pro_sales_activity.sql','20260916122000_pro_sales_reporting.sql','20260916123000_pro_sales_leaderboards.sql','20260916124000_pro_sales_goals.sql','20260916125000_pro_sales_goal_compatibility.sql','20260916126000_pro_sales_home.sql']) await db.exec(await readFile(new URL(`../migrations/${file}`,import.meta.url),'utf8'));
const actor=async n=>db.exec(`RESET ROLE;SET ROLE authenticated;SET request.jwt.claim.sub='${id(n)}'`);
const admin=async q=>{await db.exec('RESET ROLE');return (await db.exec(q)).at(-1).rows;};
const cmd=async(a,d)=>(await db.query('select field_sales_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
const target=async(a,d)=>(await db.query('select field_sales_target_command($1,$2,$3) d',[id(10),a,d])).rows[0].d;
const list=async(f={})=>(await db.query('select field_sales_target_list($1,$2) d',[id(10),f])).rows[0].d;
const {today,start,end,stamp}=(await admin("select (now() at time zone 'America/Toronto')::date::text today,date_trunc('month',now() at time zone 'America/Toronto')::date::text start,(date_trunc('month',now() at time zone 'America/Toronto')+interval '1 month - 1 day')::date::text end,now()::text stamp"))[0];
await admin(`INSERT INTO field_sales_settings(workspace_id,enabled) VALUES('${id(10)}',true); INSERT INTO field_sales_teams(id,workspace_id,name) VALUES('${id(90)}','${id(10)}','Alpha'); INSERT INTO field_sales_team_memberships(workspace_id,team_id,user_id,starts_at) VALUES('${id(10)}','${id(90)}','${id(2)}',now()-interval '90 days');`);
await admin(`UPDATE contacts SET created_at=now()-interval '90 days'; UPDATE contacts SET created_at=now()-interval '1 hour' WHERE id='${id(30)}';
 INSERT INTO contact_activities(id,contact_id,type,timestamp,status) VALUES('${id(40)}','${id(30)}','meeting',now()-interval '30 minutes','completed'),('${id(41)}','${id(31)}','meeting',now()-interval '20 minutes','completed'),('${id(42)}','${id(30)}','meeting',now()-interval '10 minutes','scheduled');
 INSERT INTO sessions VALUES('${id(50)}','${id(10)}','${id(2)}','${id(20)}');
 INSERT INTO session_events(id,session_id,building_id,created_at,event_type) VALUES('${id(51)}','${id(50)}','a',now()-interval '1 hour','conversation'),('${id(52)}','${id(50)}','a',now()-interval '30 minutes','conversation');`);
await actor(1);await cmd('settings',{currency:'CAD',timezone:'America/Toronto'});
let serial=200;const base=(scope,scope_id,metric,amount='20000')=>({request_id:id(serial++),scope,scope_id,metric,target:amount,title:`${scope} ${metric}`,starts_on:start,ends_on:end});
const companyData=base('workspace',null,'sold_value');const company=await target('create',companyData);
assert.equal((await target('create',companyData)).id,company.id);
await assert.rejects(()=>target('create',{...companyData,target:'30000'}),/already used/);
await assert.rejects(()=>target('create',{...base('workspace',null,'sold_value')}),/duplicate key/);
const rep=await target('create',base('rep',id(2),'sold_value'));
const team=await target('create',base('team',id(90),'sold_value'));
const campaign=await target('create',base('campaign',id(20),'sold_value'));
const cash=await target('create',base('workspace',null,'collected_revenue'));
const commission=await target('create',base('workspace',null,'commission'));
const close=await target('create',base('rep',id(2),'close_rate','50'));
for(const [scope,sid] of [['team',id(999)],['campaign',id(999)],['rep',id(4)]]) await assert.rejects(()=>target('create',base(scope,sid,'sales','5')),/unavailable/);
await assert.rejects(()=>target('create',base('workspace',id(2),'sales','5')),/scope ID/);
await assert.rejects(()=>target('create',base('workspace',null,'close_rate','101')),/check constraint/);
await assert.rejects(()=>target('create',base('workspace',null,'sales','1.5')),/check constraint/);
await assert.rejects(()=>target('create',null),/Invalid goal/);
const activities={};for(const metric of ['doors','conversations','leads','appointments','appointments_converted']) activities[metric]=await target('create',base('workspace',null,metric,'10'));
const sale=await cmd('submit',{request_id:id(100),contact_id:id(30),rep_id:id(2),appointment_id:id(40),value_minor:'10003',commission_minor:'1000',sold_on:today,credits:[{user_id:id(1),role:'setter',basis_points:2000},{user_id:id(2),role:'closer',basis_points:8000}]});
let rows=(await list()).goals;assert.equal(rows.find(g=>g.id===company.id).actual,'0','pending excluded');
await cmd('verify',{id:sale.id,version:1});
rows=(await list()).goals;assert.equal(rows.find(g=>g.id===company.id).actual,'10003');assert.equal(rows.find(g=>g.id===rep.id).actual,'8003');
assert.equal(rows.find(g=>g.id===team.id).actual,'10003');assert.equal(rows.find(g=>g.id===campaign.id).actual,'10003');assert.equal(rows.find(g=>g.id===commission.id).actual,'1000');
for(const [metric,n] of Object.entries({doors:'1',conversations:'1',leads:'1',appointments:'3',appointments_converted:'1'})) assert.equal(rows.find(g=>g.id===activities[metric].id).actual,n,`${metric} follows the report source definition`);
assert.equal(rows.find(g=>g.id===cash.id).actual,'0');assert.equal(rows.find(g=>g.id===close.id).pace,'insufficient_evidence');
await cmd('collect',{id:sale.id,request_id:id(101),amount_minor:'6000',occurred_at:stamp});
assert.equal((await list()).goals.find(g=>g.id===cash.id).actual,'6000');
await cmd('cancel',{id:sale.id,reason:'Customer cancelled'});
rows=(await list()).goals;assert.equal(rows.find(g=>g.id===company.id).actual,'0');assert.equal(rows.find(g=>g.id===commission.id).actual,'0');assert.equal(rows.find(g=>g.id===cash.id).actual,'6000','cancellation does not invent payment reversal');
assert.equal(rows.find(g=>g.id===activities.appointments_converted.id).actual,'0','cancelled sale no longer converts appointment cohort');
const updated=await target('update',{id:company.id,version:1,target:'40000'});assert.equal(updated.version,2);
await assert.rejects(()=>target('update',{id:company.id,version:1,target:'50000'}),/changed/);
await target('archive',{id:company.id,version:2});assert.equal((await list()).goals.some(g=>g.id===company.id),false);
await target('restore',{id:company.id,version:3});assert.equal((await list()).goals.find(g=>g.id===company.id).target,'40000');
await actor(2);rows=(await list(null)).goals;assert.equal(rows.every(g=>g.scope==='rep' && g.scope_id===id(2)),true);
await target('create',base('rep',id(2),'sales','5'));
await assert.rejects(()=>target('update',{id:company.id,version:4,target:'1'}),/access/);
await assert.rejects(()=>target('create',base('workspace',null,'sales','5')),/permission/);
await assert.rejects(()=>target('create',base('rep',id(2),'commission')),/permission/);
await actor(1);await cmd('settings',{rep_revenue_visible:false});await actor(2);
assert.equal((await list()).goals.some(g=>g.metric==='sold_value'),false);
await assert.rejects(()=>target('update',{id:rep.id,version:1,target:'2'}),/access/);
await actor(4);await assert.rejects(()=>list(),/Workspace access/);
await admin('SELECT 1');
const pace=async(actual,asOf,first='2026-03-01',last='2026-03-31',rate=false)=>(await db.query('select field_sales_target_pace($1,3100,$2,$3,$4,$5,$6) d',[actual,first,last,'America/Toronto',asOf,rate])).rows[0].d;
let p=await pace(0,'2026-02-28T12:00:00Z');assert.equal(p.pace,'not_started');assert.equal(p.days_remaining,31);assert.equal(p.projected,undefined);
p=await pace(700,'2026-03-08T05:00:00Z');assert.equal(p.projected,'3100');assert.equal(p.required_daily,'100');
p=await pace(800,'2026-03-09T04:00:00Z');assert.equal(p.projected,'3100','DST uses local calendar pace, not 24-hour timestamp intervals');
p=await pace(1000,'2026-04-02T12:00:00Z');assert.equal(p.projected,'1000');assert.equal(p.required_daily,undefined);assert.equal(p.pace,'ended');
p=await pace(3200,'2026-03-08T05:00:00Z');assert.equal(p.remaining,'0');assert.equal(p.pace,'reached');
p=await pace(-100,'2026-03-08T05:00:00Z');assert.equal(p.remaining,'3200');assert.equal(p.projected,undefined);
const events=await admin(`SELECT count(*)::int n FROM field_sales_target_events WHERE target_id='${company.id}'`);assert.equal(events[0].n,4,'retry does not duplicate audit event');
await actor(2);await assert.rejects(()=>db.query('select * from field_sales_targets'),/permission denied/);
await assert.rejects(()=>db.query('select field_sales_target_pace(1,2,current_date,current_date,\'UTC\',now(),false)'),/permission denied/);
console.log('PASS Pro Sales goals: four scopes, exact split credit, verification/reversal, cash independence, idempotency, audited edits, privacy, sample thresholds and DST pacing');await db.close();
