import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const { PGlite } = await import(process.env.PGLITE_MODULE ?? '@electric-sql/pglite');
const db = new PGlite();
const u='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002',w='00000000-0000-4000-8000-000000000003';
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY); INSERT INTO auth.users VALUES('${u}'),('${other}');
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_user::text $$;
GRANT USAGE ON SCHEMA auth TO authenticated,anon;
CREATE TABLE workspaces(id uuid PRIMARY KEY); INSERT INTO workspaces VALUES('${w}');
CREATE TABLE workspace_members(workspace_id uuid,user_id uuid); INSERT INTO workspace_members VALUES('${w}','${u}');
CREATE TABLE user_profiles(user_id uuid PRIMARY KEY,weekly_door_goal integer);
INSERT INTO user_profiles VALUES('${u}',100);
CREATE TABLE sessions(id uuid PRIMARY KEY,user_id uuid,workspace_id uuid);
CREATE TABLE session_events(id uuid,session_id uuid,building_id text,address_id uuid,event_type text,created_at timestamptz,metadata jsonb,outcome text);
CREATE TABLE contacts(id uuid PRIMARY KEY,user_id uuid,workspace_id uuid,lead_kind text,created_at timestamptz,updated_at timestamptz,reminder_date timestamptz,status text);
CREATE TABLE contact_activities(id uuid,contact_id uuid,type text,created_at timestamptz,timestamp timestamptz,note text);
INSERT INTO contacts VALUES('${u}','${u}','${w}','field',now(),now(),now()-interval '1 hour','warm'),('${other}','${other}','${w}','field',now(),now(),now()-interval '1 hour','warm');
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA public TO authenticated;
`);
for(const name of ['20260915150000_wolfy_home.sql','20260915220000_wolfy_coach.sql']) await db.exec(await readFile(new URL('../migrations/'+name,import.meta.url),'utf8'));
await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub='${u}'`);
const context=()=>db.query(`SELECT wolfy_coach_context('${w}','America/Toronto') AS c`);
const c=(await context()).rows[0].c;
assert.equal(c.overdue,1);assert.equal(c.metrics.leads,1);assert.equal(c.goals.weekly,100);
assert.ok(c.days_remaining>=1&&c.days_remaining<=7);
assert.equal(c.metrics.doors,0);
await assert.rejects(db.query(`SELECT wolfy_coach_context('${w}','invalid-zone')`));
await assert.rejects(db.query(`SELECT * FROM wolfy_coach_cache`));
await assert.rejects(db.query(`SELECT wolfy_coach_reserve('${u}')`));
await db.exec(`SET request.jwt.claim.sub='${other}'`);await assert.rejects(context());
await db.exec(`RESET ROLE; SET ROLE anon`);await assert.rejects(context());
await db.exec(`RESET ROLE; SET ROLE service_role`);
assert.equal((await db.query(`SELECT wolfy_coach_reserve('${u}') AS ok`)).rows[0].ok,true);
assert.equal((await db.query(`SELECT wolfy_coach_reserve('${u}') AS ok`)).rows[0].ok,false);
await db.exec(`RESET ROLE; UPDATE wolfy_coach_budget SET calls=30,last_call=now()-interval '10 seconds'; SET ROLE service_role`);
assert.equal((await db.query(`SELECT wolfy_coach_reserve('${u}') AS ok`)).rows[0].ok,false);
await db.exec(`RESET ROLE; UPDATE wolfy_coach_budget SET day=day-1; SET ROLE service_role`);
assert.equal((await db.query(`SELECT wolfy_coach_reserve('${u}') AS ok`)).rows[0].ok,true);
console.log('PASS coach SQL: private facts, zero activity, missing goals, invalid timezone, foreign membership, anonymous access, private cache, service-only atomic budget, cooldown, daily cap/reset');
await db.close();
