import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.PGLITE_MODULE ?? '@electric-sql/pglite');
const db=new PGlite();
const u='00000000-0000-0000-0000-000000000001', w='00000000-0000-0000-0000-000000000002', other='00000000-0000-0000-0000-000000000003';
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;
CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$SELECT current_user::text$$;
GRANT USAGE ON SCHEMA auth TO authenticated;
CREATE TABLE workspaces(id uuid PRIMARY KEY);CREATE TABLE workspace_members(workspace_id uuid,user_id uuid);
CREATE TABLE user_profiles(user_id uuid PRIMARY KEY,weekly_door_goal integer);
CREATE TABLE sessions(id uuid PRIMARY KEY,user_id uuid,workspace_id uuid);
CREATE TABLE session_events(id uuid PRIMARY KEY,session_id uuid,building_id text,address_id uuid,event_type text,created_at timestamptz,metadata jsonb,outcome text);
CREATE TABLE contacts(id uuid PRIMARY KEY,user_id uuid,workspace_id uuid,lead_kind text,created_at timestamptz,status text,phone text,email text,address text);
CREATE TABLE contact_activities(id uuid PRIMARY KEY,contact_id uuid,type text,created_at timestamptz);
INSERT INTO auth.users VALUES('${u}'),('${other}');INSERT INTO workspaces VALUES('${w}');INSERT INTO workspace_members VALUES('${w}','${u}');
INSERT INTO user_profiles VALUES('${u}',NULL);
GRANT SELECT ON workspace_members,user_profiles,sessions,session_events,contacts,contact_activities TO authenticated;
`);
await db.exec(await readFile(new URL('../migrations/20260915150000_wolfy_home.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20260915170000_wolfy_character.sql',import.meta.url),'utf8'));
await db.exec(`SET request.jwt.claim.sub='${u}';SET ROLE authenticated;`);
const call=async(sql)=>(await db.query(sql)).rows;
await call(`SELECT wolfy_snapshot('${w}','${u}')`);
await assert.rejects(call(`SELECT wolfy_purchase('${w}','${u}','cap','00000000-0000-0000-0000-000000000005')`));
await assert.rejects(call(`SELECT wolfy_award('${w}','${u}','verified_sale','fake')`));
await assert.rejects(call(`UPDATE wolfy_profiles SET coins=100000`));
await db.exec(`RESET ROLE;`);
await call(`SELECT wolfy_award('${w}','${u}','verified_sale','verified-server-event')`);
await call(`SELECT wolfy_award('${w}','${u}','verified_sale','verified-server-event')`);
await call(`SELECT wolfy_award('${w}','${u}','qualified_lead','lead-1')`);
await call(`SELECT wolfy_award('${w}','${u}','appointment','appointment-1')`);
let wallet=(await call(`SELECT xp,coins FROM wolfy_profiles`))[0];assert.equal(wallet.xp,340);assert.equal(wallet.coins,170);
await db.exec(`SET ROLE authenticated;`);
const purchase=`SELECT wolfy_purchase('${w}','${u}','cap','00000000-0000-0000-0000-000000000005')`;
await call(purchase);await call(purchase);
await call(`SELECT wolfy_purchase('${w}','${u}','cap','00000000-0000-0000-0000-000000000006')`);
wallet=(await call(`SELECT xp,coins FROM wolfy_profiles`))[0];assert.equal(wallet.xp,340);assert.equal(wallet.coins,20);
await assert.rejects(call(`SELECT wolfy_purchase('${w}','${u}','hard_hat','00000000-0000-0000-0000-000000000007')`));
await call(`SELECT wolfy_equip('${w}','${u}','cap',true)`);await call(`SELECT wolfy_equip('${w}','${u}','cap',true)`);
assert.equal((await call(`SELECT * FROM wolfy_equipment`)).length,1);
await assert.rejects(call(`SELECT wolfy_equip('${w}','${u}','gold_chain',true)`));
await call(`SELECT wolfy_interact('${w}','${u}','feed')`);await assert.rejects(call(`SELECT wolfy_interact('${w}','${u}','feed')`));
await call(`SELECT wolfy_interact('${w}','${u}','train','ask_permission')`);await call(`SELECT wolfy_interact('${w}','${u}','train','ask_permission')`);
assert.equal((await call(`SELECT xp FROM wolfy_profiles`))[0].xp,350);
await assert.rejects(call(`UPDATE wolfy_ledger SET coins=10000`));
await db.exec(`RESET ROLE;`);
const id=(await call(`SELECT id FROM wolfy_ledger WHERE source_event='purchase'`))[0].id;
await call(`SELECT wolfy_refund('${id}')`);await call(`SELECT wolfy_refund('${id}')`);
assert.equal((await call(`SELECT coins FROM wolfy_profiles`))[0].coins,175);
await assert.rejects(call(`DELETE FROM wolfy_ledger`));
await db.exec(`SET ROLE authenticated;SET request.jwt.claim.sub='${other}';`);
await assert.rejects(call(`SELECT wolfy_snapshot('${w}','${u}')`));
assert.equal((await call(`SELECT * FROM wolfy_inventory`)).length,0);
await db.exec(`RESET ROLE;
INSERT INTO contacts VALUES('00000000-0000-0000-0000-000000000090','${u}','${w}','field',now(),'hot_lead','5551112222',NULL,'A');
UPDATE contacts SET phone='5551113333' WHERE id='00000000-0000-0000-0000-000000000090';
INSERT INTO contacts VALUES('00000000-0000-0000-0000-000000000091','${u}','${w}','field',now(),'hot_lead','5551112222',NULL,'A');
`);
assert.equal((await call(`SELECT count(*)::integer AS n FROM wolfy_ledger WHERE reason='qualified_lead'`))[0].n,2); // one fixture award, one deduped business lead
await db.exec(`CREATE TABLE field_sales(id uuid PRIMARY KEY,workspace_id uuid,contact_id uuid,rep_id uuid,status text,verified_by uuid,verified_at timestamptz);`);
await db.exec(await readFile(new URL('../migrations/20260915200000_wolfy_field_sales_rewards.sql',import.meta.url),'utf8'));
const beforeSales=(await call(`SELECT xp FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0].xp;
await db.exec(`INSERT INTO field_sales VALUES('00000000-0000-0000-0000-000000000080','${w}','00000000-0000-0000-0000-000000000090','${u}','pending',NULL,NULL);`);
assert.equal((await call(`SELECT xp FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0].xp,beforeSales);
await db.exec(`UPDATE field_sales SET status='verified',verified_by='${other}',verified_at=now();`);
assert.equal((await call(`SELECT xp FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0].xp,beforeSales+250);
await db.exec(`UPDATE field_sales SET status='cancelled';INSERT INTO field_sales VALUES('00000000-0000-0000-0000-000000000081','${w}','00000000-0000-0000-0000-000000000090','${u}','verified','${other}',now());`);
assert.equal((await call(`SELECT xp FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0].xp,beforeSales+250);
// XP portrait store upgrade and preservation of legacy purchasing power.
const legacy=(await call(`SELECT xp,coins FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0];
await db.exec(await readFile(new URL('../migrations/20260915210000_wolfy_portrait_store.sql',import.meta.url),'utf8'));
assert.equal((await call(`SELECT spendable_xp FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0].spendable_xp,legacy.coins);
await call(`SELECT wolfy_award('${w}','${u}','verified_sale','xp-store-seed')`);
await call(`SELECT wolfy_award('${w}','${u}','verified_sale','xp-store-seed')`);
await call(`SELECT wolfy_award('${w}','${u}','campaign','xp-store-campaign')`);
let upgraded=(await call(`SELECT xp,spendable_xp,coins,wolfy_level(xp) AS level FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0];
assert.equal(upgraded.xp,legacy.xp+350);assert.equal(upgraded.spendable_xp,legacy.coins+350);assert.equal(upgraded.coins,legacy.coins);
await db.exec(`SET request.jwt.claim.sub='${u}';SET ROLE authenticated;`);
await assert.rejects(call(`UPDATE wolfy_profiles SET spendable_xp=999999`));
await assert.rejects(call(`SELECT wolfy_award('${w}','${u}','verified_sale','client-forgery')`));
await assert.rejects(call(`SELECT wolfy_purchase('${w}','${u}','gold_chain','00000000-0000-0000-0000-000000000050')`));
const portraitPurchase=`SELECT wolfy_purchase_portrait('${w}','${u}','portrait_chain_gold','00000000-0000-0000-0000-000000000051')`;
await call(portraitPurchase);await call(portraitPurchase);
await assert.rejects(call(`SELECT wolfy_purchase_portrait('${w}','${u}','portrait_glasses_classic','00000000-0000-0000-0000-000000000051')`));
let afterPurchase=(await call(`SELECT xp,spendable_xp,wolfy_level(xp) AS level FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0];
assert.equal(afterPurchase.xp,upgraded.xp);assert.equal(afterPurchase.level,upgraded.level);assert.equal(afterPurchase.spendable_xp,upgraded.spendable_xp-400);
assert.equal((await call(`SELECT item_id FROM wolfy_equipment WHERE slot='neck'`))[0].item_id,'portrait_chain_gold');
await call(`SELECT wolfy_purchase_portrait('${w}','${u}','portrait_chain_gold','00000000-0000-0000-0000-000000000052')`);
assert.equal((await call(`SELECT spendable_xp FROM wolfy_profiles`))[0].spendable_xp,afterPurchase.spendable_xp);
await assert.rejects(call(`SELECT wolfy_purchase_portrait('${w}','${u}','portrait_chain_cuban','00000000-0000-0000-0000-000000000053')`));
assert.equal((await call(`SELECT count(*)::int AS n FROM wolfy_inventory WHERE item_id='portrait_chain_cuban'`))[0].n,0);
await assert.rejects(call(`SELECT wolfy_equip('${w}','${u}','portrait_chain_cuban',true)`));
await call(`SELECT wolfy_purchase_portrait('${w}','${u}','portrait_collar_orange','00000000-0000-0000-0000-000000000054')`);
assert.equal((await call(`SELECT count(*)::int AS n FROM wolfy_equipment WHERE slot='neck'`))[0].n,1);
assert.equal((await call(`SELECT item_id FROM wolfy_equipment WHERE slot='neck'`))[0].item_id,'portrait_collar_orange');
await call(`SELECT wolfy_equip('${w}','${u}','portrait_collar_orange',false)`);
assert.equal((await call(`SELECT count(*)::int AS n FROM wolfy_equipment WHERE slot='neck'`))[0].n,0);
await call(`SELECT wolfy_equip('${w}','${u}','portrait_chain_gold',true)`);
await db.exec(`RESET ROLE;`);
const refundTransaction=(await call(`SELECT id FROM wolfy_ledger WHERE source_event='portrait_purchase' AND related_entity='portrait_chain_gold'`))[0].id;
await call(`SELECT wolfy_refund('${refundTransaction}')`);await call(`SELECT wolfy_refund('${refundTransaction}')`);
assert.equal((await call(`SELECT spendable_xp FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0].spendable_xp,upgraded.spendable_xp-75);
assert.equal((await call(`SELECT xp FROM wolfy_profiles WHERE workspace_id='${w}' AND user_id='${u}'`))[0].xp,upgraded.xp);
await db.exec(`SET ROLE authenticated;SET request.jwt.claim.sub='${other}';`);
await assert.rejects(call(`SELECT wolfy_purchase_portrait('${w}','${u}','portrait_glasses_classic','00000000-0000-0000-0000-000000000055')`));
await assert.rejects(call(`SELECT wolfy_purchase_portrait('${w}','${other}','portrait_glasses_classic','00000000-0000-0000-0000-000000000056')`));
assert.equal((await call(`SELECT * FROM wolfy_equipment`)).length,0);
await assert.rejects(call(`SELECT wolfy_refund('${refundTransaction}')`));
await db.exec(`RESET ROLE;`);
assert.equal((await call(`SELECT count(*)::int AS n FROM wolfy_catalog WHERE render_kind='portrait' AND price_currency='xp'`))[0].n,16);
const portraitSource=await readFile(new URL('../../WolfGrid/Features/Wolfy/WolfyPortraitAccessories.swift',import.meta.url),'utf8');
const definitions=[...portraitSource.matchAll(/\.init\(key:"([^"]+)",name:"([^"]+)",slot:"([^"]+)",price:(\d+)\)/g)];
assert.equal(definitions.length,16);
for (const [,key,name,slot,price] of definitions) {
 const row=(await call(`SELECT name,category,price,asset FROM wolfy_catalog WHERE id='portrait_${key}'`))[0];
 assert.deepEqual(row,{name,category:slot,price:Number(price),asset:key});
}
console.log('PASS: XP conversion, paired rewards, unchanged lifetime XP/rank, atomic purchase/equip, duplicate purchase protection, low balance rollback, owner-only wallet/inventory, slot replacement and idempotent refunds');
await db.close();console.log('PASS: immutable XP, award/purchase/refund idempotency, balances, locked items, ownership, equip, cooldown, training cap, verified-sale integration/recreation protection, RLS and client mutation rejection');
