import Link from 'next/link';
import { LegalPage } from '@/components/social/LegalPage';

export const metadata = {
  title: 'WolfSocial Privacy Policy',
  description: 'How WolfSocial collects, uses, stores and deletes account and connected-platform data.',
};

const providers = 'Facebook Pages, Instagram professional accounts, TikTok, YouTube, and LinkedIn';

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" updated="Effective August 5, 2026 · Last updated August 6, 2026" sections={[
    ['Who we are', <p key="who">WolfSocial is a social publishing and engagement service operated by WolfGrid in Ontario, Canada. This policy explains how WolfSocial (“WolfSocial,” “WolfGrid,” “we,” “us”) handles personal information when you use social.wolfgrid.app, the embedded WolfGrid Sales experience, or the WolfGrid Sales iOS application. Questions can be sent to <a className="underline" href="mailto:support@wolfgrid.app">support@wolfgrid.app</a>.</p>],
    ['Information we collect', <div key="collect" className="space-y-3"><p><strong>Account data:</strong> name, email address, authentication identifiers, workspace membership and settings.</p><p><strong>Connected-platform data:</strong> provider, account or Page identifier, display name, avatar, permissions, encrypted access and refresh tokens, and token expiry information for {providers}.</p><p><strong>Content and media:</strong> captions, titles, images, videos, drafts, schedules, publishing settings and provider responses that you submit through WolfSocial.</p><p><strong>Engagement data:</strong> supported comments, replies, Page or professional-account messages, contact identifiers and post analytics made available by a connected provider.</p><p><strong>Technical data:</strong> IP address, device/browser information, timestamps, request and security logs, error details and product usage events.</p></div>],
    ['How information is collected', <p key="sources">We receive information directly from you, from your organization or WolfSocial workspace, automatically when you use the service, and from a social provider after you deliberately authorize WolfSocial through that provider’s OAuth consent screen.</p>],
    ['How we use information', <ul key="uses" className="list-disc space-y-2 pl-5"><li>Authenticate users and maintain WolfSocial workspaces.</li><li>Connect accounts and display the accounts you selected.</li><li>Upload, schedule or publish content only after your explicit action.</li><li>Retrieve publishing status, supported comments, messages and analytics.</li><li>Send replies only after you review and approve them.</li><li>Provide assistive Wolfey caption and reply suggestions; Wolfey does not publish autonomously.</li><li>Provide support, diagnose failures, prevent fraud and secure the service.</li><li>Comply with legal obligations and enforce our Terms.</li></ul>],
    ['TikTok Content Posting API', <div key="tiktok" className="space-y-3"><p>WolfSocial uses TikTok data only to provide user-requested account connection, creator information, video/photo upload, Direct Post when approved, draft delivery, publishing status and available metrics.</p><p>Before any TikTok post, you select the account, privacy level and interaction settings and provide explicit approval. WolfSocial never chooses a default privacy level and never publishes or replies automatically.</p><p>For a TikTok draft upload, the media is delivered to your TikTok inbox. You must open the TikTok notification, review or edit the content, and complete publication inside TikTok.</p></div>],
    ['Google API Services and YouTube data', <div key="google" className="space-y-3"><p>When you connect a YouTube channel, WolfSocial uses Google API Services to identify the channel, upload videos that you explicitly approve, retrieve publishing status and supported analytics, synchronize comments, and send replies that you explicitly submit.</p><p>WolfSocial does not sell Google user data, use it for advertising, or publish YouTube content or replies without your action. You may disconnect the channel in WolfSocial or revoke access in your Google Account settings.</p><p>WolfSocial’s use and transfer to any other app of information received from Google APIs will adhere to the <a className="text-red-600 underline" href="https://developers.google.com/terms/api-services-user-data-policy" rel="noreferrer" target="_blank">Google API Services User Data Policy</a>, including the Limited Use requirements.</p></div>],
    ['Legal bases and consent', <p key="bases">We process information to provide the service you request, with your consent when connecting a provider, for our legitimate interests in operating and securing WolfSocial, and when required by law. You may withdraw provider access at any time by disconnecting the account or revoking WolfSocial in the provider’s settings.</p>],
    ['How we disclose information', <div key="sharing" className="space-y-3"><p>We disclose information only as needed to operate WolfSocial: to the connected provider when you request an action; to infrastructure, database, storage, authentication, email, analytics and AI subprocessors acting for us; to your workspace members according to their permissions; or when required by law or a valid legal process.</p><p>We do not sell personal information, provider data or connected-account data. We do not share it for cross-context behavioural advertising.</p></div>],
    ['Storage, security and international processing', <p key="security">Provider tokens are encrypted at rest and transmitted using HTTPS. Access is limited by workspace membership and row-level security. We use access controls, logging, backups and reasonable administrative and technical safeguards. No online service can guarantee absolute security. Our providers may process information in Canada, the United States and other countries where they operate, subject to contractual and legal safeguards.</p>],
    ['Retention', <div key="retention" className="space-y-3"><p>Connected-account tokens are retained until you disconnect the account, revoke access, delete the workspace or the token expires and is no longer needed. Drafts, media, posts, interactions and analytics remain while your workspace is active or until you delete them.</p><p>One-time OAuth state records expire after approximately ten minutes. Operational and security records may be retained only as reasonably necessary for security, dispute resolution, legal compliance and backup recovery. When deletion is requested, active data is removed after verification and residual backup copies age out through normal backup rotation.</p></div>],
    ['Your choices and privacy rights', <ul key="rights" className="list-disc space-y-2 pl-5"><li>Access, correct or export eligible personal information.</li><li>Disconnect any social account and revoke provider permissions.</li><li>Delete content, media, connections or your WolfSocial workspace.</li><li>Object to or restrict certain processing where applicable.</li><li>Withdraw consent without affecting earlier lawful processing.</li><li>Complain to an applicable privacy regulator.</li></ul>],
    ['Data deletion', <p key="delete">Use the in-product connection and deletion controls or follow our <Link className="text-red-600 underline" href="/data-deletion">Data Deletion Instructions</Link>. You may also email support@wolfgrid.app from your account email with the subject “WolfSocial data deletion.” We verify ownership before deleting account data.</p>],
    ['Children', <p key="children">WolfSocial is a professional service and is not directed to children under 13. Users must also meet the minimum age and eligibility requirements of every connected provider. We do not knowingly collect personal information from children.</p>],
    ['Changes to this policy', <p key="changes">We may update this policy as WolfSocial or legal requirements change. We will update the date above and provide additional notice when a material change requires it. Continued use after an effective update means the revised policy applies.</p>],
    ['Contact', <p key="contact">Privacy inquiries: <a className="text-red-600 underline" href="mailto:support@wolfgrid.app">support@wolfgrid.app</a>. Operator: WolfGrid, Ontario, Canada.</p>],
  ]}/>;
}
