'use client';

import { useCallback, useEffect, useState } from 'react';
import { Check, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useWorkspace } from '@/lib/workspace-context';

type Task = { id: string; title: string; due_at?: string | null; task_type: string; sales_leads?: { name?: string } | null; sales_contacts?: { name?: string } | null };
type Automation = { id: string; name: string; trigger_type: string; is_enabled: boolean };

export function FollowUpWorkspace() {
  const { currentWorkspaceId } = useWorkspace(); const [tasks, setTasks] = useState<Task[]>([]); const [automations, setAutomations] = useState<Automation[]>([]); const [title, setTitle] = useState(''); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!currentWorkspaceId) return; const suffix = `?workspaceId=${encodeURIComponent(currentWorkspaceId)}`; const [tasksResponse, automationsResponse] = await Promise.all([fetch(`/api/tasks${suffix}`), fetch(`/api/automations${suffix}`)]); const taskData = await tasksResponse.json(); const automationData = await automationsResponse.json(); if (tasksResponse.ok) setTasks(taskData.tasks ?? []); else setError(taskData.error); if (automationsResponse.ok) setAutomations(automationData.automations ?? []); }, [currentWorkspaceId]);
  useEffect(() => { void load(); }, [load]);
  async function createTask() { if (!title.trim() || !currentWorkspaceId) return; const response = await fetch(`/api/tasks?workspaceId=${encodeURIComponent(currentWorkspaceId)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, dueAt: new Date(Date.now() + 86400_000).toISOString() }) }); const data = await response.json(); if (!response.ok) setError(data.error); else { setTitle(''); await load(); } }
  async function complete(id: string) { if (!currentWorkspaceId) return; await fetch(`/api/tasks?workspaceId=${encodeURIComponent(currentWorkspaceId)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status: 'completed' }) }); await load(); }
  return <div className="mx-auto max-w-6xl p-6"><div className="mb-6"><h1 className="text-2xl font-semibold">Follow Up</h1><p className="text-sm text-muted-foreground">The action queue that keeps every lead moving.</p></div>{error ? <p className="mb-4 text-sm text-destructive">{error}</p> : null}<div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section><div className="mb-3 flex gap-2"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Call back tomorrow…" /><Button onClick={() => void createTask()}><Plus className="h-4 w-4" /> Add</Button></div><div className="divide-y rounded-xl border bg-card">{tasks.length ? tasks.map((task) => <div key={task.id} className="flex items-center gap-3 p-4"><button onClick={() => void complete(task.id)} className="grid h-8 w-8 place-items-center rounded-full border hover:bg-emerald-50"><Check className="h-4 w-4" /></button><div><p className="font-medium">{task.title}</p><p className="text-xs text-muted-foreground">{task.sales_contacts?.name || task.sales_leads?.name || task.task_type}{task.due_at ? ` · ${new Date(task.due_at).toLocaleString()}` : ''}</p></div></div>) : <p className="p-8 text-center text-sm text-muted-foreground">Nothing due. New follow-ups appear here.</p>}</div></section><aside className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Sequences</h2><p className="mb-4 text-xs text-muted-foreground">Published, versioned automations</p><div className="space-y-2">{automations.map((automation) => <div key={automation.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><p className="font-medium">{automation.name}</p><span className={`text-xs ${automation.is_enabled ? 'text-emerald-600' : 'text-muted-foreground'}`}>{automation.is_enabled ? 'Live' : 'Paused'}</span></div><p className="text-xs text-muted-foreground">Trigger: {automation.trigger_type.replaceAll('_', ' ')}</p></div>)}</div></aside></div></div>;
}
