import Link from 'next/link';
import { LegalPage } from '@/components/social/LegalPage';

export const metadata = {
  title: 'WolfSocial Terms of Service',
  description: 'Terms governing use of WolfSocial web, embedded Sales and iOS services.',
};

export default function TermsPage() {
  return <LegalPage title="Terms of Service" updated="Effective August 5, 2026 · Last updated August 5, 2026" sections={[
    ['Agreement', <p key="agreement">These Terms form an agreement between you and WolfGrid, the operator of WolfSocial in Ontario, Canada. They govern social.wolfgrid.app, WolfSocial inside WolfGrid Sales, and the WolfGrid Sales iOS experience. By creating an account or using WolfSocial, you agree to these Terms and our <Link className="text-red-600 underline" href="/privacy">Privacy Policy</Link>.</p>],
    ['Eligibility and accounts', <p key="eligibility">You must be legally able to enter this agreement, meet the age requirements of each connected platform, and provide accurate account information. You are responsible for safeguarding your credentials and for activity performed through your account. Notify support@wolfgrid.app promptly about suspected unauthorized access.</p>],
    ['Authority over connected accounts', <p key="authority">You may connect and act for a social profile, Page, channel or organization only when you own it or have valid authorization from its owner. You represent that you have all permissions required to upload, schedule, publish, moderate and analyze the content and accounts you select.</p>],
    ['Your content and licence', <div key="content" className="space-y-3"><p>You retain ownership of content you submit. You grant WolfSocial a limited, worldwide, non-exclusive licence to host, process, reproduce, format, transmit and display that content solely to operate the features you request.</p><p>You represent that your content and its use do not infringe copyright, trademark, privacy, publicity or other rights and comply with law and provider policies. This licence ends when the content is deleted, subject to reasonable backup and legal retention.</p></div>],
    ['Publishing approval', <p key="approval">WolfSocial does not autonomously publish posts or send replies. You must select the target account, review the content and settings, and approve each immediate post, scheduled post or reply. Scheduled delivery can continue server-side after your device closes. You remain responsible for reviewing content before approval.</p>],
    ['TikTok uploads and Direct Post', <div key="tiktok" className="space-y-3"><p>When using TikTok Direct Post, you must manually select privacy and other required settings, confirm applicable music and commercial-content rights, and explicitly approve the exact post.</p><p>When using TikTok draft upload, WolfSocial transfers the media to TikTok for further review. You must open the TikTok inbox notification and complete the editing and posting flow inside TikTok. A successful draft transfer is not a representation that the content has become public.</p></div>],
    ['Acceptable use', <ul key="acceptable" className="list-disc space-y-2 pl-5"><li>Do not publish unlawful, fraudulent, deceptive, defamatory, hateful, harassing, exploitative or infringing material.</li><li>Do not distribute malware, spam, artificial engagement or unauthorized automated content.</li><li>Do not impersonate others, misrepresent authority, evade platform safeguards or circumvent rate limits.</li><li>Do not scrape, reverse engineer or probe WolfSocial or connected providers except where law expressly permits.</li><li>Do not upload personal or confidential data unless you have a lawful basis and authorization.</li><li>Do not use Wolfey suggestions without reviewing their accuracy, rights and suitability.</li></ul>],
    ['Third-party platforms', <p key="providers">Facebook, Instagram, TikTok, YouTube and LinkedIn are independent services. Your use remains subject to their terms, community guidelines, music and commercial-content rules, API permissions and account restrictions. Providers may change, limit, reject, delay or remove content and functionality. WolfSocial cannot override provider decisions or guarantee approval, reach or availability.</p>],
    ['Wolfey assistance', <p key="wolfey">Wolfey may suggest captions and responses. Suggestions may be incomplete or inaccurate and are not legal, professional or factual advice. Nothing is published or sent without your approval. You are responsible for verifying claims, permissions, disclosures and compliance.</p>],
    ['Service availability and changes', <p key="availability">We may maintain, improve, limit, suspend or discontinue features. Publishing can be delayed or fail because of outages, processing times, expired authorization, provider review, rate limits or unsupported media. We may suspend access when reasonably necessary to protect users, providers, WolfSocial or the public.</p>],
    ['Intellectual property', <p key="ip">WolfSocial, its software, interface, branding and documentation are owned by WolfGrid or its licensors. These Terms do not transfer those rights. Provider names and trademarks belong to their respective owners and do not imply endorsement.</p>],
    ['Termination and deletion', <p key="termination">You may stop using WolfSocial, disconnect providers or request deletion at any time. We may suspend or terminate access for a material breach, unlawful activity, security risk or provider requirement. After termination, provisions that by nature should survive—including ownership, disclaimers, liability and dispute terms—remain effective.</p>],
    ['Disclaimers', <p key="disclaimer">To the maximum extent permitted by law, WolfSocial is provided “as is” and “as available.” We disclaim implied warranties of merchantability, fitness for a particular purpose, non-infringement and uninterrupted or error-free operation. Nothing in these Terms excludes warranties or rights that cannot lawfully be excluded.</p>],
    ['Limitation of liability', <p key="liability">To the maximum extent permitted by law, WolfGrid will not be liable for indirect, incidental, special, consequential, exemplary or punitive damages, loss of profits, goodwill, data, reach or business opportunity arising from WolfSocial or a provider. WolfGrid’s aggregate liability for a claim will not exceed the amount you paid for WolfSocial during the twelve months before the event giving rise to the claim, or CAD $100 if you paid nothing, except where applicable law does not permit that limitation.</p>],
    ['Indemnity', <p key="indemnity">To the extent permitted by law, you will defend and indemnify WolfGrid from third-party claims arising from your content, connected accounts, violation of these Terms, law, provider rules or another person’s rights.</p>],
    ['Governing law', <p key="law">These Terms are governed by the laws of Ontario and the federal laws of Canada applicable there, without regard to conflict-of-law rules. Courts located in Ontario have exclusive jurisdiction, unless consumer law requires another forum.</p>],
    ['Changes', <p key="changes">We may update these Terms. We will change the date above and provide additional notice when legally required. If you do not agree to an update, stop using WolfSocial before it takes effect.</p>],
    ['Contact', <p key="contact">Questions about these Terms: <a className="text-red-600 underline" href="mailto:support@wolfgrid.app">support@wolfgrid.app</a>. Operator: WolfGrid, Ontario, Canada.</p>],
  ]}/>;
}
